branchName: '${issue.number}-${issue.title,}'
gitSafeReplacementChar: '-'
autoCloseIssue: true
branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/
  - label: release
    prefix: release/
  - label: hotfix
    prefix: hotfix/
